kill-death-messages: true
mysql:
    host: localhost
    port: 3306
    username: root
    database: warriors
    password: test
    player_data_table: player_data
    minConnections: 1
    maxConnections: 5
    connectionTimeout: 0
    testQuery: "SELECT 1"